### ISSUE TITLE
Game plan

### ISSUE THREAD

**Issue by blahajj** [blahajj/multi-layer-finRAG#4]
Right now we have a pipeline with RAG that pulls data from a vector database when prompted. The pipeline can now answer simple questions like whats the earnings per share of the company.

Next steps:

1. Try different embedding semantics -- Poojitha -- let us know if you are fine with this
2. Add higher-level questions for robustness testing -- @blahajj 
3. Add a second layer of LLM -- @ritu1412

**Comment by midspooj** [comment]
I'm fine with that, let me start working on the same tonight
